### ISSUE TITLE
Support for Angular 7

### ISSUE THREAD

**Issue by ravivit9** [benbaran/adal-angular4#106]
HI, 
At the moment I am using adal-angular6 version which is failing up on upgrading Angular to version 7.  

I would like to know future plans to support Angular 7 version.

Thanks,
Ravindra.

**Comment by ravivit9** [comment]
Hi @benbaran, I uninstalled adal-angular6 and intstalled adal-angular4 and upgraded to angular 7 as suggested in the readme file.  I am not sure whether adal-angular4 supports http get, patch, post and delete methods similar to adal-angular6.

Thanks.

**Comment by benbaran** [comment]
It uses the native HttpClient, so it will support all operations. Be sure to follow the adal-angular-6-example to get the HTTP_INTERCEPTORS set up properly to send the token with the requests.

**Comment by ravivit9** [comment]
Hi @benbaran, I am getting the following error after upgrading to angular 7 using adal-angular6.  That's the reason I am looking for another solution to sort this out.

<img width="1093" alt="screenshot 2018-12-12 at 11 54 10" src="https://user-images.githubusercontent.com/3435829/49868225-aec0df00-fe04-11e8-8f6e-8e5a03d69fa7.png">

**Comment by benbaran** [comment]
That’s not my library, so I can’t speak to it, unfortunately. This one (adal-angular4) does work with Angular 7 though. The example project has been updated, and I tested it yesterday.

**Comment by ravivit9** [comment]
Hi, @benbaran, now I have uninstalled the adal-angular6 and using yours.  it's working fine.  Thanks for your support.

**Comment by akshayantony** [comment]
Hi @benbaran, i checkedout the adal-angular4 code from [link](https://github.com/benbaran/adal-angular4) and performed the commands as in the read me file. **How can i run the code?** When i execute `ng serve` command, i am getting this **error** `The serve command requires to be run in an Angular project, but a project definition could not be found.`. It may be because your code doesnot have angular.json or angular-cli.json file. Please help
