### ISSUE TITLE
Seamless token refresh

### ISSUE THREAD

**Issue by TheAifam5** [benbaran/adal-angular4#124]
Hey,
Currently I using the default way for authentication like:
```
this.adalService.handleWindowCallback();

    if (!this.adalService.userInfo.authenticated) {
      this.adalService.login();

      return;
    }
```

The problem is, that the page after a minutes, refreshes the page completely and redirects to Microsoft, then back to the application.

Is there a better way to refresh the token without refreshing the whole page?

Regards,
TheAifam5

**Comment by rwoody** [comment]
You probably want `this.adalService.acquireToken();`. The `login()` method always redirects you.

**Comment by TheAifam5** [comment]
Lets say the user is already authenticated. The problem is, that after some time the page gets completely refreshed automatically. The question is, how can i avoid the refresh and do it silently?

**Comment by rwoody** [comment]
I’m using an access token for services. They expire after an hour. Even after they expire, using ‘acquireToken()’ the access token is refreshed without a redirect.

That said, not all apps using this library need to use access tokens per the design (eg. only using an ID token for accessing the backend on the same host as the client side app). Typically with OAuth 2 flows, once the ID token (in OAuth terms, the refresh token) expires, the only way to refresh it is do it a full login (redirecting, etc. which interrupts the UX). I’m not sure what you can do in these circumstances because none of the client libraries for ADAL have thorough documentation on how to use them or on token refresh behavior, and I haven’t read the docs/specs on Microsoft’s side.

**Comment by TheAifam5** [comment]
That works only if u have the refresh token. In SPA application, using the implicit flow authentication, the server does not sends the refresh token. In example of Microsoft ADFS, its disabled due to security issues. :/ Need to find an alternative.

**Comment by jesuslpm** [comment]
@TheAifam5, I have the same issue, after an hour the page is refreshed. Did you find a working solution?

**Comment by TheAifam5** [comment]
@jesuslpm yes. You need to change your authentication flow. The Implicit Flow does not send the refresh token, because of security issues etc... Consider to use Authentication Code Grant Flow.

**Comment by jesuslpm** [comment]
@TheAifam5 thanks. Please, let me know if you find that library. I would be much appreciated :-)

**Comment by JACrazy** [comment]
The one solution that had worked for me is to use popup for sign in. The only problem I encountered though is if the active directory redirects the login to a custom organization Microsoft login page URL, everything breaks in Edge because Edge cant communicate between security zones. Edge support was a requirement for my situation so this didnt work. If just using the normal Microsoft login page URL, it works as a solution.

**Comment by arnevdv** [comment]
Is there an update on this?

**Comment by JACrazy** [comment]
So I've figured out something that works, basically use acquireToken and if a token doesn't come back, sign the user in.
Most of this is ripped right from the logic of the adalService refreshLoginToken()

After the `this.adalService.handleWindowCallback();` do this:
```
    this.adalService.acquireToken(this.adalService.config.loginResource).subscribe(token => {
      this.adalService.userInfo.token = token;
      if (this.adalService.userInfo.authenticated == false) {
        this.adalService.userInfo.authenticated = true;
        this.adalService.userInfo.error = '';
      }
    }, error => {
      this.adalService.userInfo.authenticated = false;
      this.adalService.userInfo.error = error;
      this.adalService.login();
    });
```

Also you will need to set css in styles.css to hide the iframe
```
iframe#adalIdTokenFrame{
  display:none
}

```

**Comment by rangeranger** [comment]
Same problem here. Is there a way at least to refresh to the current URL? My app refresh to the main URL. We display the app on screens and it is making us change the URL every hour.

**Comment by ADNewsom09** [comment]
> Same problem here. Is there a way at least to refresh to the current URL? My app refresh to the main URL. We display the app on screens and it is making us change the URL every hour.
@rangeranger 

@JACrazy's response worked for us.

**Comment by yepyao** [comment]
I got the same issue and investigate for some time. I think the root cause is the `user.authenticated` in `adal.service.ts` doesn't set to true in the 'adalIdTokenFrame' iframe.

### RCA
When the token expire and `refreshLoginToken()` be called, the adal-angular lib will insert an iframe with id 'adalIdTokenFrame' into the main page, which is hidden so you cannot see it. This iframe will be navigate to "https://login.microsoftonline.com/microsoft.onmicrosoft.com/oauth2/authorize", and this url will redirect the iframe to your app's page, which also runs the adal-angular4 module. (This is why you may see two app module ngOnInit called in console if you add log) 

In this in-frame app, the 'AdalService.context' is shared with the main page, but not share the the 'AdalService.user'. Also when `handleWindowCallback` be called, the` requestInfo.requestType` is 'RENEW_TOKEN' which make it fail to set `user.authenticated` to true.  

Then if you write `if (!this.adalService.userInfo.authenticated) { this.adalService.login() }` in your app.component.ts. This will lead another login() called, which finally refresh the main page.

### Solution: 

Add check `window.self === window.top`  before any `login()`/`logout()` called, to make sure the login/logout method won't be called in iframe.
```
if (!this.adalService.userInfo.authenticated && window.self === window.top) {
    this.adalService.clearCache();
    this.adalService.login();
}
```

**Comment by benbaran** [comment]
Thanks for looking into it! I don’t have as much time as I used to to look after this library. If you have a fix, please feel free to put in a pull request : )
