### ISSUE TITLE
Reply URL with query Params

### ISSUE THREAD

**Issue by ankitsalu** [benbaran/adal-angular4#126]
My reply URL specified in azure is https://Sales/PricingSearch

and i want to load the page from some other application like https://Sales/PricingSearch?price=10

If i am logged in, it validates this reply url i.e. https://Sales/PricingSearch?price=10, and let me use the application.
but in case I am not logged in, then instead of giving an option to login, i get the error reply url invalid.

Also, Azure is recently upgraded and now its not allowing to me to use wildcard in reply URL. 

Please suggest?

**Comment by jesuslpm** [comment]
Reply url with parameters doesn't work. I suggest you to use sessionStorage to store the parameter and then use the last stored value to go to the desired route when Azure redirect to you reply Url page.

**Comment by ankitsalu** [comment]
thanks for getting back. I have this link https://Sales/PricingSearch?price=10, in an EMAIL. So the email link directly takes me to the application, so won't have  a chance to store the values in sessionStorage before. Our user would like to access the link directly which would populate the page based on Query params...

If i am logged in, it validates this reply url i.e. https://Sales/PricingSearch?price=10, and let me use the application.
but in case I am NOT logged in, then instead of giving an option to login, i get the error reply url invalid.

**Comment by jesuslpm** [comment]
@ankitsalu. Yes you do have a chance to store the values in sessionStorage.

This is how I'm doing it:

I have an authentication guard that prevents navigating to protected routes in my application. If the user is not authenticated the authentication guard navigates to the login component, passing the current url to the login component as `returnUrl` parameter.

To figure out `returnUrl`, the login component look at `returnUrl` query parameter first, if it is not present, it looks at session storage, if it is not there, it assumes it is the home page. Then, If the user is authenticated, the login component navigates to returnUrl. If the user is not authenticated the login component stores `returnUrl` into session storage and calls adal.login().

Using this techinque, and setting ReplayUrl to https://Sales/login, when the user points the browser to https://Sales/PricingSearch?price=10, because the user is not authenticates, the authentication guard navigates to https://Sales/login?returnUrl=%2FPricingSearch%3Fprice%3D10 . Because the user is not authenticated, the login component stores returnUrl into the session storage and shows the Azure AD login page. When the user enter login and password and redirects to https://Sales/login, the user is authenticated, there is not returnUrl query parameter, but returnUrl is in session storage, and the login component navigates to /PricingSearch?price=10.

All the code is in [this gist](https://gist.github.com/jesuslpm/d9b6b26ef9b4e365c71283a3131b6c22). 

I'm using popup windows because it prevents whole page reload when id token expires after an hour. But this technique works on both popup and redirect mode.

**Comment by ankitsalu** [comment]
@jesuslpm  - thanks a lot for your help. guard is the place which gives me a chance to store values in SessionStorage before adal comes into the picture. many thanks again.
