### ISSUE TITLE
Infinite loop - Internet Explorer

### ISSUE THREAD

**Issue by saltfoundry** [benbaran/adal-angular4#5]
Successful authentication with Internet Explorer is resulting in an infinite loop between the redirect_URI and Azure AD. Is anyone else seeing this?

**Comment by LastTribunal** [comment]
I did see it once in Edge

**Comment by wzhgba** [comment]
Try adding this into configuration object to see if helps (default session storage which has different behavior between browsers):
cacheLocation: 'localStorage'

**Comment by geerzo** [comment]
Is this still an issue?

**Comment by pytek** [comment]
Hi, I found similar problem using adal-angular4 3.0.10 and Google Chrome Version 68.0.3440.106 (I used cacheLocation: 'localStorage') with AAD. 
When token expired and adal.js call to AAD and in the same time user refresh page, my app still infinitive loop.
I investigated this problem and found what is wrong.
In adal.service.js in function **init** is condition:
`if (this.user.loginCached && !this.user.authenticated && window.self == window.top) {
            this.refreshLoginToken();
        }`
values:
- this.user.loginCached (TRUE)
- this.user.authenticated (FALSE, because AAD redirect to my page with #id_token and adal.service.js hasn't set up this property yet)
- window.self == window.top (TRUE)

method refreshLoginToken() is fired while #id_token is returned from AAD.
@geerzo what do you think if condition will look like:
` if (this.user.loginCached && !this.user.authenticated && window.self == window.top && !this.isInCallbackRedirectMode) {
            this.refreshLoginToken();
        }`

**isInCallbackRedirectMode**:
`    private get isInCallbackRedirectMode(): boolean {
      return window.location.href.indexOf("#access_token") !== -1 || window.location.href.indexOf("#id_token") !== -1;
    }`

**Comment by geerzo** [comment]
@pytek this shouldn't cause an infinite loop as the refreshLoginToken happens in the background (iframe) but I still like your change suggestion. How do you reproduce it?

BTW - 3.0.10 is broken, use 3.0.7 for now.

**Comment by pytek** [comment]
@geerzo I change value of key adal.expiration.keyXXXX in storage to epoch in past to force refresh token, at the same time I click refresh page.

Now I found similar infinitive loop when adal.expiration.keyXXXX expired and I open tab with my app

**Comment by geerzo** [comment]
@pytek do me a favor and try 3.0.7 and see if you have the same problem.

**Comment by pytek** [comment]
@geerzo I will downgrade library version to 3.0.7 and back with feedback :)

**Comment by pytek** [comment]
@geerzo I downgraded library to version 3.0.7 and I have same problem. 
My app still try refresh token on **init** function after back **id_token** from AAD, when id_token back to my app. See attachment

![image](https://user-images.githubusercontent.com/3649077/44860137-e2bd2d80-ac75-11e8-9909-c9c64f4fc965.png)

**Comment by geerzo** [comment]
Ok, I'll take a look at adding a fix.
