### ISSUE TITLE
How to config token expiry time

### ISSUE THREAD

**Issue by FrankyHuQingFeng** [benbaran/adal-angular4#54]
The default token expiry time is one hour. However I want to test token renew which will make me wait for one hour. 

When i search online, I find https://docs.microsoft.com/en-us/azure/active-directory/active-directory-configurable-token-lifetimes which have the "AccessTokenLifetime" and I also see "expireOffsetSeconds" for the adal-angular4 config. However both of them are not working.

Anyone can help?

**Comment by geerzo** [comment]
That documentation are AAD settings, not client settings. They are global to your AAD instance. You have to configure them via PowerShell with these [commands](https://docs.microsoft.com/en-us/azure/active-directory/active-directory-configurable-token-lifetimes#cmdlet-reference).

Since this isn't a client library issue I'm going to close the issue.
