### ISSUE TITLE
Adal Angular 1.0.15 to 1.0.17

### ISSUE THREAD

**Issue by kameelyan** [benbaran/adal-angular4#91]
I noticed that this wrapper forces version 1.0.15 for adal-angular, are there any plans to update to 1.0.17?

**Comment by rahulraibit** [comment]
I don't know why this library is still using 1.0.15 version of adal angular. Please update to 1.0.17. This will solve acquire token issue during first time login because I have noticed in 1.0.17 version we have options to pass loadFrameTimeout which is not available for 1.0.15. This frameTimeout issue which is keep coming to many user because default LOADFRAME_TIMEOUT: '6000'.

**Comment by leonixyz** [comment]
The reason is that with the release of adal-angular 1.0.16  Microsoft changed the library API, but the version was still released as a "patch" ([see comment](https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/690#issuecomment-363071885))

**Comment by michaeltarleton** [comment]
(bump) Any plans to upgrade the adal-angular dependency?

**Comment by benbaran** [comment]
I would love to, but the code doesn’t work with newer versions. I assume it’s a bug in my code, but I don’t have time at the moment to track it down.

**Comment by geerzo** [comment]
I found a fix I believe. I've committed a change (5e97bb57622dcb786f1f1da10674fa7c2409afaa) that I believe fixes this issue and allows us to use more recent adal.js libraries.

**Comment by geerzo** [comment]
This is now fixed as part of the 4.x release.
